### ISSUE TITLE
Non-continuous page names warning message should be triggered

### ISSUE THREAD

**Issue by kmsheng** [karmapa/ketaka-lite#83]
Given 1.1a, 1.2a, 1.2b, 1.3a, 1.3b
SHOULD have output "1.1b is missing."

Given 1.1a, 1.1b, 1.2a, 1.2b, 1.2c, 1.3a, 1.3b
SHOULD have output "1.2d is missing."

Given 1.1a, 1.1b, 1.3a, 1.3b
SHOULD have output "1.2a, 1.2b are missing."

Given 1.1a, 1.1b, 2.1a, 2.1b
SHOULD NOT trigger warning because everything is fine.

**Comment by chiehan1** [comment]
And it's correct that the page number start from 1.0a or 1.1a

**Comment by chiehan1** [comment]
@lamalien says that it's ok to check the missing one "inside" assumed continuous page names, no need to check missing page names from 1.0a or 1.1a. The reason is that users may import text of range 1.100a to 1.200b, not 1.1a to 1.200b.

**Comment by kmsheng** [comment]
ok.

**Comment by chiehan1** [comment]
David:
This rule may also be added.
Given 1.1a, 1.1b, 1.1c, 1.1d, 1.2a, 1.2b, 1.3a, 1.3b, 1.3c, 1.3d
SHOULD NOT trigger warning because everything is fine.

Now in v0.1.67, it will warn that 1.2c, 1.2d might be missing. But the given pages are actually continuous without missing 1.2c and 1.2d.

Thank you!!

**Comment by kmsheng** [comment]
fixed in v0.1.69

**Comment by chiehan1** [comment]
test ok in v0.1.69 in mac and windows8
thank you
